# Checks if the target branch is not master
# If it is automatically change to development
name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check_target_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check target branch
        id: check_target_branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "master" ]; then
            echo "::set-output name=branch::development"
          else
            echo "::set-output name=branch::${{ github.event.pull_request.base.ref }}"
          fi
      - name: Change target branch
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.check_target_branch.outputs.branch }}
          branch: ${{ github.event.pull_request.head.ref }}
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          labels: ${{ github.event.pull_request.labels }}
          assignees: ${{ github.event.pull_request.assignees }}
          reviewers: ${{ github.event.pull_request.requested_reviewers }}
          team-reviewers: ${{ github.event.pull_request.requested_teams }}
          draft: ${{ github.event.pull_request.draft }}
          delete-branch: true
          close-issue: true
          branch-suffix: timestamp
          commit-message: Change target branch
          title: Change target branch
          body: |
            This pull request was automatically created because the target branch was changed.
            The original pull request was: ${{ github.event.pull_request.html_url }}
          labels: |
            target-branch-changed
          assignees: |
            peter-evans
          reviewers: |
            peter-evans
          team-reviewers: |
            peter-evans
          draft: false
          delete-branch: true
          close-issue: true
